### PR TITLE
Enhance ipcc

### PR DESCRIPTION
**Pull request by BenFaruna**
I have added the ecological zone and climate domain for all the countries and the function to calculate the average above ground biomass and implemented the test for the function.

### CODE REVIEW

**Review by axelizsak — COMMENTED** [review]
Great work on the data base, for the function it's also perfect. We'd just have to put the function and its test in a new file in the methodologies directory and not in the ipcc file.

**Comment by BenFaruna** [comment]
I have moved the averageAGB function into average_agb.cairo file in the methodologies module.

I also made changes to the visibility of TABLE3A11 function, Table3A14Data struct with it's variables and I added the module to lib.cairo.

**Comment by axelizsak** [comment]
Thanks @BenFaruna for your modifications and I'm going to ask you for one last little adjustment that I hadn't specified but which, after discussion with the team, could be more interesting. Rather than using ``if``, ``else`` it would be better to do pattern matching for the function, it's very quick to modify this and you'll find information here: https://cairo-by-example.com/examples/pattern_matching/

Thanks and have a nice day :)

**Comment by BenFaruna** [comment]
Alright, I will do that
Since there're lots of options, it might take a while
I'll let you know when I'm done

**Pull request merged**
